let options = {
    symptom_1: " abdominal_pain",
    symptom_2: " abnormal_menstruation",
    symptom_3: " acidity",
    symptom_4: " acute_liver_failure",
    symptom_5: " altered_sensorium",
    symptom_6: " anxiety",
    symptom_7: " back_pain",
    symptom_8: " belly_pain",
    symptom_9: " blackheads",
    symptom_10: "  bladder_discomfort",
    symptom_11: "  blister",
    symptom_12: "  blood_in_sputum",
    symptom_13: "  bloody_stool",
    symptom_14: "  blurred_and_distorted_vision",
    symptom_15: "  breathlessness",
    symptom_16: "  brittle_nails",
    symptom_17: "  bruising",
    symptom_18: "  burning_micturition",
    symptom_19: "  chest_pain",
    symptom_20: "  chills",
    symptom_21: "  cold_hands_and_feets",
    symptom_22: "  coma",
    symptom_23: "  congestion",
    symptom_24: "  constipation",
    symptom_25: "  continuous_feel_of_urine",
    symptom_26: "  continuous_sneezing",
    symptom_27: "  cough",
    symptom_28: "  cramps",
    symptom_29: "  dark_urine",
    symptom_30: "  dehydration",
    symptom_31: "  depression",
    symptom_32: "  diarrhoea",
    symptom_33: "  dischromic_patches",
    symptom_34: "  distention_of_abdomen",
    symptom_35: "  dizziness",
    symptom_36: "  drying_and_tingling_lips",
    symptom_37: "  enlarged_thyroid",
    symptom_38: "  excessive_hunger",
    symptom_39: "  extra_marital_contacts",
    symptom_40: "  family_history",
    symptom_41: "  fast_heart_rate",
    symptom_42: "  fatigue",
    symptom_43: "  fluid_overload",
    symptom_44: "  foul_smell_of_urine",
    symptom_45: "  headache",
    symptom_46: "  high_fever",
    symptom_47: "  hip_joint_pain",
    symptom_48: "  history_of_alcohol_consumption",
    symptom_49: "  increased_appetite",
    symptom_50: "  indigestion",
    symptom_51: "  inflammatory_nails",
    symptom_52: "  internal_itching",
    symptom_53: "  irregular_sugar_level",
    symptom_54: "  irritability",
    symptom_55: "  irritation_in_anus",
    symptom_56: "  joint_pain",
    symptom_57: "  knee_pain",
    symptom_58: "  lack_of_concentration",
    symptom_59: "  lethargy",
    symptom_60: "  loss_of_appetite",
    symptom_61: "  loss_of_balance",
    symptom_62: "  loss_of_smell",
    symptom_63: "  malaise",
    symptom_64: "  mild_fever",
    symptom_65: "  mood_swings",
    symptom_66: "  movement_stiffness",
    symptom_67: "  mucoid_sputum",
    symptom_68: "  muscle_pain",
    symptom_69: "  muscle_wasting",
    symptom_70: "  muscle_weakness",
    symptom_71: "  nausea",
    symptom_72: "  neck_pain",
    symptom_73: "  nodal_skin_eruptions",
    symptom_74: "  obesity",
    symptom_75: "  pain_behind_the_eyes",
    symptom_76: "  pain_during_bowel_movements",
    symptom_77: "  pain_in_anal_region",
    symptom_78: "  painful_walking",
    symptom_79: "  palpitations",
    symptom_80: "  passage_of_gases",
    symptom_81: "  patches_in_throat",
    symptom_82: "  phlegm",
    symptom_83: "  polyuria",
    symptom_84: "  prominent_veins_on_calf",
    symptom_85: "  puffy_face_and_eyes",
    symptom_86: "  pus_filled_pimples",
    symptom_87: "  receiving_blood_transfusion",
    symptom_88: "  receiving_unsterile_injections",
    symptom_89: "  red_sore_around_nose",
    symptom_90: "  red_spots_over_body",
    symptom_91: "  redness_of_eyes",
    symptom_92: "  restlessness",
    symptom_93: "  runny_nose",
    symptom_94: "  rusty_sputum",
    symptom_95: "  scurring",
    symptom_96: "  shivering",
    symptom_97: "  silver_like_dusting",
    symptom_98: "  sinus_pressure",
    symptom_99: "  skin_peeling",
    symptom_100: " skin_rash",
    symptom_101: "  slurred_speech",
    symptom_102: "  small_dents_in_nails",
    symptom_103: "  spinning_movements",
    symptom_104: "  spotting_urination",
    symptom_105: "  stiff_neck",
    symptom_106: "  stomach_bleeding",
    symptom_107: "  stomach_pain",
    symptom_108: "  sunken_eyes",
    symptom_109: "  sweating",
    symptom_110: "  swelled_lymph_nodes",
    symptom_111: "  swelling_joints",
    symptom_112: "  swelling_of_stomach",
    symptom_113: "  swollen_blood_vessels",
    symptom_114: "  swollen_extremeties",
    symptom_115: "  swollen_legs",
    symptom_116: "  throat_irritation",
    symptom_117: "  toxic_look_(typhos)",
    symptom_118: "  ulcers_on_tongue",
    symptom_119: "  unsteadiness",
    symptom_120: "  visual_disturbances",
    symptom_121: "  vomiting",
    symptom_122: "  watering_from_eyes",
    symptom_123: "  weakness_in_limbs",
    symptom_124: "  weakness_of_one_body_side",
    symptom_125: "  weight_gain",
    symptom_126: "  weight_loss",
    symptom_127: "  yellow_crust_ooze",
    symptom_128: "  yellow_urine",
    symptom_129: "  yellowing_of_eyes",
    symptom_130: "  yellowish_skin",
    symptom_131: " itching"
};
let myDropdown = document.getElementById("options");
let data = [];
for (let option in options) {
    var option_tag = `<a>
    <input type="checkbox"  value=${options[option]} id=${option} name='data[]'}>
    <label for=${option} style="color:#333">${options[option]}</label>
    </a>`;
    data.push(option_tag);
    myDropdown.innerHTML = data;
    function filterFunction() {
        var input, inputs, filter, ul, li, a, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        div = document.getElementById("options");
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
            txtValue = a[i].textContent || a[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "";
            } else {
                a[i].style.display = "hidden";
            }
        }
    }
}
